// <auto-generated />
using Gym_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym_Store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Gold Standard 100% Whey.jpg",
                            Name = "Optimum Nutrition Gold Standard 100% Whey French Vanilla",
                            Price = 98.95m,
                            Quantity = "2.27 kg",
                            Type = "Protein Powder"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/Gym_Store/Images/Myprotein Impact Whey Isolate.jpg",
                            Name = "Myprotein Impact Whey Isolate",
                            Price = 70.50m,
                            Quantity = "1 kg",
                            Type = "Protein Powder"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/Gym_Store/Images/INC Creatine Monohydrate.jpg",
                            Name = "INC Creatine Monohydrate",
                            Price = 39.95m,
                            Quantity = "500 g",
                            Type = "Creatine Supplement"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/Gym_Store/Images/EHP Labs Pride Pre-Workout Blue Slushie.jpg",
                            Name = "EHP Labs Pride Pre-Workout Blue Slushie",
                            Price = 79.95m,
                            Quantity = "40 Serves",
                            Type = "Pre-Workout"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/Gym_Store/Images/EHP Labs Pride Pre-Workout Raspberry Twizzle.jpg",
                            Name = "EHP Labs Pride Pre-Workout Raspberry Twizzle",
                            Price = 79.95m,
                            Quantity = "40 Serves",
                            Type = "Pre-Workout"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Gold Standard Pre-Workout Green Apple.jpg",
                            Name = "Optimum Nutrition Gold Standard Pre-Workout Green Apple",
                            Price = 39.90m,
                            Quantity = "30 Serves",
                            Type = "Pre-Workout"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Gold Standard Pre-Workout Blueberry Lemonade.jpg",
                            Name = "Optimum Nutrition Gold Standard Pre-Workout Blueberry Lemonade",
                            Price = 39.90m,
                            Quantity = "30 Serves",
                            Type = "Pre-Workout"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/Gym_Store/Images/Musashi Pre-Workout Purple Grape.jpg",
                            Name = "Musashi Pre-Workout Purple Grape",
                            Price = 29.99m,
                            Quantity = "225 g",
                            Type = "Pre-Workout"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
